import Head from "next/head";
import {
  Box,
  Flex,
  Heading,
  Text,
  Table,
  Thead,
  Tbody,
  Tfoot,
  Tr,
  Th,
  Td,
  TableCaption,
  TableContainer,
} from "@chakra-ui/react";
import { useSortBy, useTable } from "react-table";
import bt from "@/utils/bt";
import colley from "@/utils/colley";
import massey from "@/utils/massey";
import results from "../results";
import Container from "@/components/Container";

export default function Home() {
  let ratings = bt(results, 10);
  ratings = ratings.sort((a, b) => b.rating - a.rating);

  let colleyRatings = colley(results);
  colleyRatings = colleyRatings.sort((a, b) => b.rating - a.rating);

  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box as="main">
        <TableContainer>
          <Table>
            <TableCaption>SSBU Ratings</TableCaption>
            <Thead>
              <Tr>
                <Th>Place</Th>
                <Th>Team</Th>
                <Th>Pts</Th>
                <Th>Pts Avg</Th>
                <Th>Bradley-Terry Rating</Th>
                <Th>Colley Rating</Th>
              </Tr>
            </Thead>
            <Tbody>
              {ratings.map((team: any, i: number) => (
                <Tr key={team.team}>
                  <Td>{i + 1}</Td>
                  <Td>{team.team}</Td>
                  <Td>{team.wins * 2}</Td>
                  <Td>{((team.wins * 2) / team.gameCount).toFixed(2)}</Td>
                  <Td>{(10 * team.rating).toFixed(3)}</Td>
                  <Td>
                    {(
                      10 *
                      colleyRatings[
                        colleyRatings.indexOf(
                          colleyRatings.find((t: any) => t.team === team.team)
                        )
                      ].rating
                    ).toFixed(3)}
                  </Td>
                </Tr>
              ))}
            </Tbody>
          </Table>
        </TableContainer>
      </Box>
    </Container>
  );
}
