import { useRef } from "react";
import Head from "next/head";
import { Box } from "@chakra-ui/react";
import { ApiClient } from "@twurple/api";
import { TwitchPlayer } from "react-twitch-embed";
import Container from "../components/Container";

const apiClient = new ApiClient({
  authProvider: {
    clientId: "gp762nuuoqcoxypju8c569th9wz7q5",
  },
});

export default async function Home() {
  const embed = useRef();

  const handleReady = (e: any) => {
    embed.current = e;
  };

  async function isStreamLive(userName: string) {
    const user = await apiClient.users.getUserByName(userName);
    if (!user) {
      return false;
    }
    return (await user.getStream()) !== null;
  }

  const isLive = await isStreamLive("bgcuv");

  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box as="main">
        <Box>{isLive}</Box>
        <TwitchPlayer channel="bgcuv" autoplay muted onReady={handleReady} />
      </Box>
    </Container>
  );
}
